export enum EventType {
  TOURISM = 'TOURISM',
  URBAN = 'URBAN',
  OFF_ROAD = 'OFF_ROAD',
  COMPETITION = 'COMPETITION',
  SOLIDARITY = 'SOLIDARITY',
  SHORT_DISTANCE = 'SHORT_DISTANCE',
}

export enum EventDifficulty {
  EASY = 'EASY',
  MODERATE = 'MODERATE',
  MEDIUM = 'MEDIUM',
  HARD = 'HARD',
  VERY_HARD = 'VERY_HARD',
}

export enum EventState {
  DRAFT = 'DRAFT',
  SCHEDULED = 'SCHEDULED',
  IN_PROGRESS = 'IN_PROGRESS',
  CANCELLED = 'CANCELLED',
  FINISHED = 'FINISHED',
}
