export enum EventType {
  ON_ROAD = 'ON_ROAD',
  OFF_ROAD = 'OFF_ROAD',
  COURSE = 'COURSE',
  TRACK_DAY = 'TRACK_DAY',
  LEISURE = 'LEISURE',
  COMPETITION = 'COMPETITION',
}

export enum EventDifficulty {
  EASY = 'EASY',
  MODERATE = 'MODERATE',
  MEDIUM = 'MEDIUM',
  HARD = 'HARD',
  VERY_HARD = 'VERY_HARD',
}

export enum EventState {
  DRAFT = 'DRAFT',
  SCHEDULED = 'SCHEDULED',
  IN_PROGRESS = 'IN_PROGRESS',
  CANCELLED = 'CANCELLED',
  FINISHED = 'FINISHED',
}
